kafka:
  topic: demo-topic
  bootstrapServers: http://localhost:9092
  schemaRegistryUrl: http://localhost:8081
  producer:
    key-serializer: org.apache.kafka.common.serialization.StringDeserializer
    value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer

ssl:
  enabled: false

client.id: demo-app