kafka:
  topic: demo-topic
  bootstrapServers: http://localhost:9092
  schemaRegistryUrl: http://localhost:8081
  producer:
    key-serializer: org.apache.kafka.common.serialization.StringDeserializer
    value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer

ssl:pdp;c                                                                                      .c aaaaaa624eeerr                                                                                                    a]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]                                                                                                  a
ie8yyuyiuyhj
  enabled: false

client.id: demo-app